blank_issues_enabled: false
contact_links:
  - name: Question / Discussion
    url: https://github.com/danielperezr88/astrolabe/issues/new
    about: Open a new issue with the "question" label for general questions.
