/**
 * LLM-Powered Wiki Generation (#269)
 *
 * Generates per-module documentation from the knowledge graph using
 * LLM for module descriptions (when available) or community names
 * for basic offline mode.
 */

import { writeFileSync, existsSync, mkdirSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import type { KnowledgeGraph } from '../core/types.js';

export interface WikiOptions {
  repoPath: string;
  repoName: string;
  graph: KnowledgeGraph;
  /** LLM model name (default: gpt-4o-mini). */
  model?: string;
  /** LLM API base URL. */
  baseUrl?: string;
  /** LLM API key. */
  apiKey?: string;
  /** Force full regeneration (clears existing wiki). */
  force?: boolean;
}

export interface WikiResult {
  pageCount: number;
  moduleCount: number;
  overviewPath: string;
}

function callLlm(prompt: string, opts: WikiOptions, moduleName: string): Promise<string> {
  // #355: Only use OpenAI-compatible keys (OPENAI_API_KEY or explicit --api-key)
  const apiKey = opts.apiKey || process.env.OPENAI_API_KEY || '';
  if (!apiKey) return Promise.resolve('');

  const url = opts.baseUrl || 'https://api.openai.com/v1/chat/completions';
  const model = opts.model || 'gpt-4o-mini';

  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), 30_000); // #356: 30s timeout

  return fetch(url, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${apiKey}`,
    },
    body: JSON.stringify({
      model,
      messages: [{ role: 'user', content: prompt }],
      max_tokens: 500,
      temperature: 0.3,
    }),
    signal: controller.signal,
  })
    .then((r) => {
      clearTimeout(timeout);
      // #356: Check HTTP status before parsing
      if (!r.ok) throw new Error(`LLM API error: ${r.status} ${r.statusText}`);
      return r.json();
    })
    .then((data: any) => data.choices?.[0]?.message?.content || '')
    .catch((e) => {
      clearTimeout(timeout);
      if ((e as Error).name === 'AbortError') {
        console.warn(`[wiki] LLM call timed out for "${moduleName}"`);
      }
      return '';
    });
}

async function generateModuleDescription(
  moduleName: string,
  symbols: string[],
  opts: WikiOptions,
): Promise<string> {
  if (!opts.apiKey && !process.env.OPENAI_API_KEY) {
    // #355: Offline mode — only OPENAI_API_KEY supported (not Anthropic)
    return `The **${moduleName}** module contains ${symbols.length} key symbols and handles functionality related to ${moduleName.replace(/-/g, ' ')}.\n\nKey symbols: ${symbols.slice(0, 10).map((s) => `\`${s}\``).join(', ')}.`;
  }

  const prompt = `Write a 2-3 sentence description of a software module named "${moduleName}" containing these symbols: ${symbols.slice(0, 15).join(', ')}. Focus on the module's purpose and what it provides. Be concise.`;
  return callLlm(prompt, opts, moduleName);
}

export async function generateWiki(opts: WikiOptions): Promise<WikiResult> {
  const wikiDir = join(opts.repoPath, '.astrolabe', 'wiki');
  const { graph } = opts;

  // Clean existing wiki if forced
  if (opts.force && existsSync(wikiDir)) {
    rmSync(wikiDir, { recursive: true, force: true });
  }

  if (!existsSync(wikiDir)) mkdirSync(wikiDir, { recursive: true });

  // Collect communities and their symbols
  const communities = new Map<string, string[]>();
  const memberOf = new Map<string, string>();
  for (const rel of graph.iterRelationships()) {
    if (rel.type === 'MEMBER_OF') {
      const target = graph.getNode(rel.targetId);
      if (target) memberOf.set(rel.sourceId, (target.properties.name as string) ?? target.id);
    }
  }

  for (const node of graph.iterNodes()) {
    if (node.label === 'Community') {
      const name = (node.properties.name as string) ?? node.id;
      if (!communities.has(name)) communities.set(name, []);
    } else if (['Function', 'Class', 'Method', 'Interface'].includes(node.label)) {
      const cName = memberOf.get(node.id);
      if (cName) {
        if (!communities.has(cName)) communities.set(cName, []);
        communities.get(cName)!.push((node.properties.name as string) ?? node.id);
      }
    }
  }

  let pageCount = 0;
  const usedNames = new Set<string>(); // #357: collision-safe naming

  // Generate per-module pages
  for (const [name, symbols] of communities) {
    let safeName = name.replace(/[^a-zA-Z0-9_-]/g, '_');
    // #357: ensure uniqueness — append short hash if name collides
    if (usedNames.has(safeName)) {
      let hash = 0;
      for (let i = 0; i < name.length; i++) hash = ((hash << 5) - hash) + name.charCodeAt(i) | 0;
      safeName += '_' + Math.abs(hash).toString(16).slice(0, 6);
    }
    usedNames.add(safeName);
    const description = await generateModuleDescription(name, symbols, opts);

    const content = [
      `# ${name}\n`,
      `> Auto-generated by Astrolabe Wiki | ${new Date().toISOString().split('T')[0]}\n`,
      `\n## Overview\n`,
      description,
      `\n## Key Symbols (${symbols.length})\n`,
      ...symbols.slice(0, 30).map((s) => `- \`${s}\``),
      `\n## Dependencies\n`,
      `_See cross-module links in the overview page._`,
    ].join('\n');

    writeFileSync(join(wikiDir, `${safeName}.md`), content, 'utf-8');
    pageCount++;
  }

  // Generate overview page
  const overviewLines = [
    `# ${opts.repoName} — Codebase Wiki\n`,
    `> Auto-generated by Astrolabe | ${new Date().toISOString().split('T')[0]}\n`,
    `\n## Modules (${communities.size})\n`,
  ];

  for (const [name, symbols] of communities) {
    const safeName = name.replace(/[^a-zA-Z0-9_-]/g, '_');
    overviewLines.push(`- [${name}](${safeName}.md) — ${symbols.length} symbols`);
  }

  overviewLines.push(
    `\n## Index Stats\n`,
    `- Total symbols: ${graph.nodeCount}`,
    `- Total relationships: ${graph.relationshipCount}`,
    `- Communities: ${communities.size}`,
    `\n## Cross-References\n`,
    `Use \`astrolabe context <symbol>\` for 360-degree views of any symbol.`,
  );

  writeFileSync(join(wikiDir, 'README.md'), overviewLines.join('\n'), 'utf-8');

  return { pageCount, moduleCount: communities.size, overviewPath: join(wikiDir, 'README.md') };
}
