/**
 * Claude Code Hooks — auto-augmentation for AI coding agents (#276).
 *
 * Generates hook scripts and configuration for Claude Code integration:
 * - PreToolUse: Enriches grep/search results with knowledge graph context
 * - PostToolUse: Detects stale index after commits, prompts re-analysis
 *
 * Hooks are written to `.claude/hooks/` during `astrolabe analyze`.
 */

import { writeFileSync, readFileSync, mkdirSync, existsSync } from 'node:fs';
import { join } from 'node:path';

// ── Hook script templates ──────────────────────────────────────────────────

/**
 * PreToolUse hook script (JavaScript, runs in Claude Code environment).
 *
 * Intercepts file discovery and search operations, enriching results
 * with symbol context from the Astrolabe knowledge graph.
 */
const PRE_TOOL_USE_SCRIPT = `#!/usr/bin/env node
/**
 * Astrolabe PreToolUse Hook — enriches tool results with knowledge graph context.
 *
 * Intercepts: Grep, Glob, LS, Read, Bash(find), Bash(grep), Bash(rg)
 * For each discovered file, queries the Astrolabe MCP server for:
 * - Symbols defined in the file
 * - Process membership (which flows does this file participate in?)
 * - Community membership (which functional cluster?)
 *
 * Generated by: astrolabe analyze
 */

const { execSync } = require('child_process');
const { existsSync } = require('fs');
const path = require('path');

function getAstrolabeCli() {
  // Try local npx first, then global
  try {
    return 'npx @astrolabe-dev/cli';
  } catch {
    return 'astrolabe';
  }
}

function querySymbols(filePath, repoRoot) {
  try {
    const relPath = path.relative(repoRoot, filePath).replace(/\\\\/g, '/');
    const dbPath = path.join(repoRoot, '.astrolabe', 'astrolabe.db');
    const result = require('child_process').execFileSync(
      'npx', ['-y', '@astrolabe-dev/cli', 'list', '--label', 'Function', '--db', dbPath],
      { encoding: 'utf-8', timeout: 5000, stdio: ['ignore', 'pipe', 'ignore'] },
    );
    const lines = result.split('\\n').filter(l => l.includes(relPath));
    return lines.slice(0, 15);
  } catch {
    return [];
  }
}

function getToolInput(hookInput) {
  // Parse Claude Code hook input JSON from stdin
  // #326: Use fd 0 instead of /dev/stdin for Windows compatibility
  try {
    const raw = require('fs').readFileSync(0, 'utf-8');
    return JSON.parse(raw);
  } catch {
    return hookInput || {};
  }
}

// ── Main ──
const input = getToolInput(process.env.CLAUDE_HOOK_INPUT);
const toolName = input?.tool_name || input?.toolName || '';
const toolInput = input?.tool_input || input?.toolInput || {};

// Only enrich file-discovery tools
const SEARCH_TOOLS = ['Grep', 'Glob', 'LS', 'Read', 'Bash'];
if (!SEARCH_TOOLS.some(t => toolName.includes(t))) {
  process.exit(0);
}

// Find repo root (look for .astrolabe)
let repoRoot = process.cwd();
while (repoRoot !== path.parse(repoRoot).root) {
  if (existsSync(path.join(repoRoot, '.astrolabe', 'astrolabe.db'))) break;
  repoRoot = path.dirname(repoRoot);
}
if (!existsSync(path.join(repoRoot, '.astrolabe', 'astrolabe.db'))) {
  process.exit(0);
}

// Extract file paths from tool input
const filePaths = [];
const inputStr = JSON.stringify(toolInput);
const fpRegex = /([a-zA-Z0-9_\\/\\.-]+\\.(ts|tsx|js|jsx|py|java|go|rs|php|rb|swift|c|cpp|dart|kt))/g;
let m;
while ((m = fpRegex.exec(inputStr)) !== null) {
  filePaths.push(m[1]);
}

if (filePaths.length === 0) process.exit(0);

// Enrich with graph context
const enrichments = [];
for (const fp of filePaths.slice(0, 5)) {
  const symbols = querySymbols(fp, repoRoot);
  if (symbols.length > 0) {
    enrichments.push(\`  \${fp}: \${symbols.join(', ')}\`);
  }
}

if (enrichments.length > 0) {
  console.error('\\n[astrolabe] Knowledge graph context:');
  console.error(enrichments.join('\\n'));
  console.error('[astrolabe] Use astrolabe context <symbol> for 360-degree view\\n');
}

process.exit(0);
`;

/**
 * PostToolUse hook script (JavaScript, runs in Claude Code environment).
 *
 * After git commits, checks if HEAD has changed since the last analysis.
 * If the index is stale, prompts the agent to re-run astrolabe analyze.
 */
const POST_TOOL_USE_SCRIPT = `#!/usr/bin/env node
/**
 * Astrolabe PostToolUse Hook — stale index detection after commits.
 *
 * After Write, Edit, or Bash(git commit) operations, checks whether
 * git HEAD has advanced past the last-indexed commit in meta.json.
 * If stale, prompts the agent to re-index.
 *
 * Generated by: astrolabe analyze
 */

const { execSync } = require('child_process');
const { existsSync, readFileSync } = require('fs');
const path = require('path');

function getToolInput(hookInput) {
  try {
    const raw = require('fs').readFileSync(0, 'utf-8');
    return JSON.parse(raw);
  } catch {
    return hookInput || {};
  }
}

// Only check after modifications
const input = getToolInput(process.env.CLAUDE_HOOK_INPUT);
const toolName = input?.tool_name || input?.toolName || '';
const MODIFY_TOOLS = ['Write', 'Edit', 'Bash'];
if (!MODIFY_TOOLS.some(t => toolName.includes(t))) {
  process.exit(0);
}

// Only check if git commit was involved (for Bash tool)
if (toolName === 'Bash') {
  const cmd = input?.tool_input?.command || input?.toolInput?.command || '';
  if (!cmd.includes('git commit') && !cmd.includes('git add')) {
    process.exit(0);
  }
}

// Find repo root
let repoRoot = process.cwd();
while (repoRoot !== path.parse(repoRoot).root) {
  if (existsSync(path.join(repoRoot, '.git'))) break;
  repoRoot = path.dirname(repoRoot);
}
if (!existsSync(path.join(repoRoot, '.git'))) {
  process.exit(0);
}

// Check meta.json
const metaPath = path.join(repoRoot, '.astrolabe', 'meta.json');
if (!existsSync(metaPath)) process.exit(0);

try {
  const meta = JSON.parse(readFileSync(metaPath, 'utf-8'));
  if (!meta.lastCommit) process.exit(0);

  const currentHead = execSync('git rev-parse HEAD', {
    cwd: repoRoot, encoding: 'utf-8', timeout: 3000
  }).trim();

  if (currentHead !== meta.lastCommit) {
    console.error('\\n[astrolabe] Knowledge graph is stale!');
    console.error(\`[astrolabe] Last indexed: \${meta.lastCommit.substring(0, 7)}\`);
    console.error(\`[astrolabe] Current HEAD: \${currentHead.substring(0, 7)}\`);
    console.error('[astrolabe] Run: astrolabe analyze . --skip-workers\\n');
  }
} catch {
  // Silent fail — hook should never block the agent
}

process.exit(0);
`;

// ── Hook configuration ─────────────────────────────────────────────────────

/**
 * Generate the hooks.json configuration for Claude Code.
 */
export function generateHooksConfig(): object {
  return {
    description: 'Astrolabe knowledge graph hooks — enriches tool results and detects stale indexes',
    hooks: [
      {
        type: 'PreToolUse',
        matchers: ['Grep', 'Glob', 'LS', 'Read'],
        hooks: [
          {
            type: 'command',
            command: 'node .claude/hooks/astrolabe-pre-tool-use.js',
          },
        ],
      },
      {
        type: 'PostToolUse',
        matchers: ['Write', 'Edit', 'Bash'],
        hooks: [
          {
            type: 'command',
            command: 'node .claude/hooks/astrolabe-post-tool-use.js',
          },
        ],
      },
    ],
  };
}

/**
 * Install hook scripts into the .claude/hooks/ directory of a repository.
 *
 * Creates the directory if it doesn't exist, writes the two hook scripts
 * and the hooks.json configuration file.
 *
 * @param repoPath — Absolute path to the repository root.
 */
export function installHooks(repoPath: string): { scripts: number; config: boolean } {
  const hooksDir = join(repoPath, '.claude', 'hooks');

  if (!existsSync(hooksDir)) {
    mkdirSync(hooksDir, { recursive: true });
  }

  // #327: Only write hook scripts if they don't exist (idempotent)
  const prePath = join(hooksDir, 'astrolabe-pre-tool-use.js');
  const postPath = join(hooksDir, 'astrolabe-post-tool-use.js');
  let scriptsWritten = 0;

  if (!existsSync(prePath)) {
    writeFileSync(prePath, PRE_TOOL_USE_SCRIPT, 'utf-8');
    scriptsWritten++;
  }
  if (!existsSync(postPath)) {
    writeFileSync(postPath, POST_TOOL_USE_SCRIPT, 'utf-8');
    scriptsWritten++;
  }

  // #327: Merge Astrolabe hooks into existing hooks.json instead of overwriting
  const configPath = join(hooksDir, 'hooks.json');
  let existingConfig: any = { hooks: [] };

  if (existsSync(configPath)) {
    try {
      existingConfig = JSON.parse(readFileSync(configPath, 'utf-8'));
    } catch {
      // Corrupt config — start fresh
      existingConfig = { hooks: [] };
    }
  }

  // Ensure hooks array exists
  if (!Array.isArray(existingConfig.hooks)) {
    existingConfig.hooks = [];
  }

  // Check if Astrolabe hooks are already registered
  const astrolabePre = existingConfig.hooks.some(
    (h: any) => h.type === 'PreToolUse' && h.hooks?.some((sh: any) => sh.command?.includes('astrolabe-pre-tool-use')),
  );
  const astrolabePost = existingConfig.hooks.some(
    (h: any) => h.type === 'PostToolUse' && h.hooks?.some((sh: any) => sh.command?.includes('astrolabe-post-tool-use')),
  );

  const newHooks = generateHooksConfig() as any;
  let merged = false;

  if (!astrolabePre || !astrolabePost) {
    for (const hook of newHooks.hooks) {
      const isPre = hook.type === 'PreToolUse';
      if ((isPre && !astrolabePre) || (!isPre && !astrolabePost)) {
        existingConfig.hooks.push(hook);
        merged = true;
      }
    }

    if (merged) {
      writeFileSync(configPath, JSON.stringify(existingConfig, null, 2), 'utf-8');
    }
  }

  return { scripts: scriptsWritten, config: merged || (!astrolabePre && !astrolabePost) };
}
